server:
  port: 8888

spring:
  output:
    ansi:
      enabled: always
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
