server:
  port: 8090

spring:
  output:
    ansi:
      enabled: always
  application:
    name: mvsc-greeting

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/